[MeterBar0]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed0]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar1]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed1]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar2]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed2]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar3]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed3]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar4]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed4]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar5]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed5]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar6]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed6]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar7]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed7]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar8]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed8]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar9]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed9]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar10]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed10]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar11]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed11]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar12]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed12]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar13]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed13]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar14]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed14]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar15]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed15]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar16]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed16]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar17]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed17]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar18]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed18]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar19]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed19]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar20]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed20]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar21]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed21]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar22]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed22]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar23]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed23]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar24]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed24]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar25]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed25]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar26]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed26]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar27]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed27]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar28]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed28]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar29]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed29]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar30]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed30]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar31]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed31]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar32]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed32]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar33]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed33]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar34]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed34]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar35]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed35]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar36]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed36]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar37]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed37]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar38]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed38]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar39]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed39]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar40]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed40]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar41]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed41]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar42]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed42]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar43]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed43]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar44]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed44]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar45]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed45]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar46]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed46]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar47]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed47]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar48]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed48]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar49]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed49]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar50]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed50]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar51]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed51]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar52]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed52]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar53]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed53]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar54]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=15R
Y=980
Shape=Rectangle 0,0,(30*1.0),(-(980-(30*1.0))*[MeasureAudioSmoothed54]-(30*1.0)),((30*1.0)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1